# =========================
# journal/event_types.py — TradingPalantir
# Типы событий журнала (§22 спека).
# =========================
SKILL_CALLED        = "SKILL_CALLED"
EVIDENCE_ADDED      = "EVIDENCE_ADDED"
REGIME_UPDATED      = "REGIME_UPDATED"
SCORE_UPDATED       = "SCORE_UPDATED"          # скоринг монеты (1..100) + разбивка
WATCHLIST_UPDATED   = "WATCHLIST_UPDATED"      # топ-20
ARMED_SET_UPDATED   = "ARMED_SET_UPDATED"      # score >= порога
CANDIDATE_FOUND     = "CANDIDATE_FOUND"
TRADE_SIGNAL_CREATED= "TRADE_SIGNAL_CREATED"
LLM_ANALYSIS_CREATED= "LLM_ANALYSIS_CREATED"
LLM_REVIEW_CREATED  = "LLM_REVIEW_CREATED"
TRADE_REJECTED      = "TRADE_REJECTED"
RISK_APPROVED       = "RISK_APPROVED"
RISK_REJECTED       = "RISK_REJECTED"
ORDER_SUBMITTED     = "ORDER_SUBMITTED"
ORDER_FILLED        = "ORDER_FILLED"
STOP_MOVED          = "STOP_MOVED"
RIDE_MODE_ON        = "RIDE_MODE_ON"
EXIT_WARNING        = "EXIT_WARNING"
PARTIAL_CLOSE       = "PARTIAL_CLOSE"
FULL_CLOSE          = "FULL_CLOSE"
FALLBACK_TRADE      = "FALLBACK_TRADE"
DAILY_TRADE_CHECK   = "DAILY_TRADE_REQUIREMENT_CHECK"
DRAWDOWN_TRIGGERED  = "DRAWDOWN_GUARD_TRIGGERED"
FIREWALL_REJECTED   = "FIREWALL_REJECTED"
TIGHT_STOP_SKIP     = "TIGHT_STOP_SKIP"
MFI_GATE_SKIP       = "MFI_GATE_SKIP"
